# from datasets import load_dataset
from transformers import AutoModelForSeq2SeqLM
from transformers import AutoTokenizer
from transformers import GenerationConfig
from nltk.corpus import stopwords
import pandas as pd
from nltk.stem import PorterStemmer
from tqdm import tqdm
from langdetect import detect
import pickle

model_name='google/flan-t5-base'
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('input_dir', help='The directory of emotion file generated by Emotion_Detection_Midi_data')
    parser.add_argument('output_dir', help='The output directory')
    args = parser.parse_args()
    model = model.to(device)
    input_path = args.input_dir
    output_path = args.output_dir
    res = []
    for n in range(1,10):
        file = open(input_path + '/lakh_lyric'+str(n)+'.bin','rb')
        music_data1 = pickle.load(file)
        file.close()
        for i in tqdm(range(len(music_data1))):
            # embedding = np.zeros(100)
            # count = 0
            m = music_data1[i]
            if m[0].shape[0]>=612:
                try:
                    query = """
                    What's the emotion of this lyrics:
                    Oh-oh
                    Mmm
                    Well, I wonder, could it be
                    When I was dreaming 'bout you baby, you were dreaming of me
                    Call me crazy
                    Call me blind
                    To still be suffering is stupid after all of this time
                    Did I lose my love to someone better
                    And does she love you like I do, I do
                    You know I really, really do
                    Well, hey, so much I need to say
                    Been lonely since the day
                    The day you went away
                    So sad but true, for me there's only you
                    Been crying since the day
                    The day you went away
                    In the doorway with your case
                    No longer shouting at each other, there were tears on our faces
                    And we were letting go of something special
                    Something we'll never have again
                    I know, I guess I really, really know
                    Well hey, so much I need to say
                    Been lonely since the day
                    The day you went away
                    So sad but true for me there's only you
                    Been crying since the day
                    The day you went away
                    The day you went away
                    The day you went away
                    The answer should be only one word.
                    sad


                    What's the emotion of this lyrics:
                    Do you hear the people sing?
                    Singing the song of angry men?
                    It is the music of the people
                    Who will not be slaves again!
                    When the beating of your heart
                    Echoes the beating of the drums
                    There is a life about to start
                    When tomorrow comes!
                    Will you join in our crusade?
                    Who will be strong and stand with me?
                    Beyond the barricade
                    Is there a world you long to see?
                    Then join in the fight
                    That will give you the right to be free!
                    The answer should be only one word.
                    angry

                    What's the emotion of this lyrics: \n"""+m[1].lower()+""". \n The answer should be only one word."""# from alert, excited, happy, content, relaxed, calm, bored, depressed, sad, distressed, angry, and tense"""#+ """amusing, annoying, anxious, beautiful, calm, dreamy, energizing, erotic, indignant, joyful, sad, scary, triumphant"""#"""Anger, Annoyance, Contempt, Disgust, Irritation, Anxiety, Embarrassment, Fear, Helplessness, Powerlessness, Worry, Doubt, Envy, Frustration, Guilt, Shame, Boredom, Despair, Disappointment, Hurt, Sadness, Stress, Shock, Tension, Amusement, Delight, Elation, Excitement, Happiness, Joy, Pleasure, Affection, Empathy, Friendliness, Love, Pride, Courage, Hope, Humility, Satisfaction, Trust, Calmness, Contentment, Relaxation, Relief, Serenity, Interest, Politeness, Surprise""".lower()
                    inputs = tokenizer(query, return_tensors='pt').to(device)
                    output = tokenizer.decode(
                        model.generate(
                            inputs['input_ids'],
                            max_new_tokens=50,
                        )[0],
                        skip_special_tokens=True
                    )
                    # temp.append([s[:-2], output])
                    res.append([m[0][100:612], output])
                except:
                    pass
    file = open(args.output_dir + '/lakh_emotion.bin','wb')
    pickle.dump(res,file)
    file.close()